### ISSUE TITLE
[INPUT] Text (or Speech) Length of Blaser 2.0

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/SONAR#22]
For translation quality estimation of Blaser 2.0, I think there is no limitation of the text (or the speech) length. However, from my personal perspective, I do not think the estimation will be accurate if the text (or the speech) is too long.

So, what text length and speech length (of source, reference, and hypothesis) do you recommend?

**Comment by avidale** [comment]
SONAR was trained as a *sentence encoder*, so it expects the source, reference, and hypothesis to be single sentences.

Speech (or transcribed text without punctuation) is not always easy to segment into sentences, you can think of 30 seconds maximum as a rule of thumb. 

Also, please check out the discussions of input lengths in the Seamless Communication repo (https://github.com/search?q=repo%3Afacebookresearch%2Fseamless_communication+length&type=issues), because Seamless and SONAR models were trained on similar tasks and similar data.
