### ISSUE TITLE
Language Code Mappings [Text & Speech]

### ISSUE THREAD

**Issue by ai-nikolai** [facebookresearch/SONAR#23]
Hi Team,

Is there a clear mapping between languages in the two letter format (e.g. en, de, fr, pt, ...) to the format present for Sonar. Is there a conversion script somewhere, or a clear mapping and explanation of the language codes?

Particular, it seems there is a speech format:
https://github.com/facebookresearch/SONAR/blob/main/sonar/cards/sonar_speech_encoder.yaml

And there is a text format:
https://github.com/facebookresearch/SONAR/blob/main/sonar/cards/text_sonar_basic_encoder.yaml

Thank you.

**Comment by ai-nikolai** [comment]
E.g. for example compared to this table:
http://www.lingoes.net/en/translator/langcode.htm

**Comment by avidale** [comment]
Hi Nikolai!
We use (mostly) the same language codes throughout several projects: [FLORES](https://github.com/facebookresearch/flores/blob/main/flores200/README.md) (its readme file contains the language names!), [NLLB](https://github.com/facebookresearch/fairseq/tree/nllb/), [Seamless](https://github.com/facebookresearch/seamless_communication/blob/main/docs/m4t/README.md), and SONAR. They always consist of a 3-letter language code specified in [ISO 639-3](https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes) and a 4-letter script code specified in [ISO 15924](https://unicode.org/iso15924/iso15924-codes.html). You can refer to these standards to determine the language. Also, you may want to consult https://glottolog.org/, which lists language codes in multiple standards. Finally, you may want to use the [langcodes](https://github.com/rspeer/langcodes) Python package to convert between those language codes automatically, although it not always 100% accurate.

Please be aware that the relation between the two-letter codes and the SONAR-style codes is not always a bijection, because several SONAR-style codes may refer to the same two-letter codes, and some SONAR-style codes do not have a corresponding two-letter code at all. Some examples:
- `ace_Arab` and `ace_Latn` both refer to the Acehnese language, but written in different scripts. This language doesn't have a two-letter code.
- `azj_Latn` (North Azerbaijani written in Latin script) and `azb_Arab` (South Azerbaijani written in Arabic script) both have the two-letter code `az` (which doesn't specify the dialect);

**Comment by avidale** [comment]
Another interesting example is Chinese. `zho_Hans` and `zho_Hant` both mean "Chinese" (which has the two-letter code `zh`), but written in two different scripts: either simplified or traditional Chinese characters. For historical reasons, the simplified characters are used mostly in the mainland China, and the traditional characters are used nowadays mostly in Taywan, so you may see these two varieties being referred to as `zh-CN` and `zh-TW`. However, this is not entirely correct for two reasons:
  - In some countries (e.g. Singapore), both scripts are used. So, for example, when you see a text written in traditional characters, you cannot say whether it is from Taiwan, Singapore, or maybe from mainland China before the orthography reform, and associating it with a specific country has a high chance of mistake. And in general, when speaking about languages, it is much more correct to use just linguistic terms instead of geopolitical ones.
  - Even the name "Chinese language" is ambiguous, because linguistically speaking, some of its dialects are distinct languages that are not mutually understandable. In mainland China and Taiwan, Mandarin (three-letter code `cmn`) is the official language, whereas in Hong Kong and Macau, it is Cantonese (`yue`), although it is still called "Chinese". And there are a lot of other varieties!  Because of that, to be less confusing, we started using the code `cmn` for Mandarin (so the speech encoder uses it instead of  more confusing `zho`). 

As you can see, identifying the right language variety may be a non-trivial and even sensitive issue. So if in doubt, please contact a linguist or a native speaker.

**Comment by ai-nikolai** [comment]
Hi David,

Thank you very much for this excellent response and really interesting additional information. I would vote this up on stackoverflow ;). 

Super interesting, thanks again. 

I am happy with the answer and will continue investigating and keep you posted in case there are some additional questions or insights.
