### ISSUE TITLE
change max seq len

### ISSUE THREAD

**Issue by gulldan** [facebookresearch/SONAR#5]
Is it a way to change max_seq_len from 514 to 1024 for example?
or somehow compute current seq_len of text to avoid long texts, tokenizer hasnt method to return tokens.

**Comment by artemru** [comment]
yes, you can easily modify it in `SonarSpeechEncoderBuilder` like this for instance :
`self.config.w2v2_encoder_config.max_seq_len *= 2`
(code around https://github.com/facebookresearch/SONAR/blob/main/sonar/models/sonar_speech/builder.py#L159) 
Similar overwrite will work for TextEncoders as well. Since we dont expose this param outside, you can create/register your own config where you set this params to the wanted value.

**Comment by gulldan** [comment]
> yes, you can easily modify it in SonarSpeechEncoderBuilder like this for instance :
> self.config.w2v2_encoder_config.max_seq_len *= 2
> (code around https://github.com/facebookresearch/SONAR/blob/main/sonar/models/sonar_speech/builder.py#L159)
> Similar overwrite will work for TextEncoders as well. Since we dont expose this param outside, you can create/register your own config where you set this params to the wanted value.

so no issues, backward incompatibilities for max_seq_len for exp 10_000 instead of 512?

**Comment by artemru** [comment]
there may be some impact predictive impact but it should be limited (due to relative positional encoding), yet I would say it's safer to validate extrapolations the results for your concrete case.
