### ISSUE TITLE
Possible languages specific Alternative Spelling or Capitalization Rules alignment issue for future improvement SONAR cross-lingual vector space or BLASER quality measure alignment

### ISSUE THREAD

**Issue by Fikavec** [facebookresearch/SONAR#6]
Problem description for possible scientific research and more details: [Alternative Spelling rules in some languages for benchmarking embeddings models](https://github.com/facebookresearch/flores/issues/26)

Colab for reproduce (.ipynb and .py) with SONAR and BLASER quick test: 
[SONAR_BLASER_Alternative_Spelling_or_Capitalization_Rules_TEST.zip](https://github.com/facebookresearch/SONAR/files/12440030/SONAR_BLASER_Alternative_Spelling_or_Capitalization_Rules_TEST.zip)

For SONAR and BLASER2 we can observe a **decrease** (sometimes significant) for the **similarity metric** of words/sentences written **in Alternative Spelling** or **[Capitalization Rules](https://www.studygermanonline.com/blog/when-to-use-capital-letters-in-german)**:
- **Word-level results (EN-DE, same EN-DE word in Alternative Spelling):**
  ![image](https://github.com/facebookresearch/SONAR/assets/83672821/08bd3add-4406-44fc-844a-584d2a4c4d08)
- **Word-level results (DE-DE word in Alternative Spelling):** 
![image](https://github.com/facebookresearch/SONAR/assets/83672821/e8daf028-73bb-4f68-b2e2-2cd65dcc698b)
- **Word-level results (EN-DE test [Capitalization Rules](https://www.studygermanonline.com/blog/when-to-use-capital-letters-in-german)):** 
![image](https://github.com/facebookresearch/SONAR/assets/83672821/c676cdca-c0a4-4661-9bda-aad6610fb9f2)

- **Sentence-level (EN-DE, same EN-DE with German Alternative Spelling and Capitalization Rules) results:**
  ![image](https://github.com/facebookresearch/SONAR/assets/83672821/4d897aeb-aadb-49da-b30e-b02bf6c96f82)
- **Sentence-level (one German language, sentence with words written in Alternative Spelling) results:**
  ![image](https://github.com/facebookresearch/SONAR/assets/83672821/2a885092-91b2-4810-90fa-61a52a26310b)

**Comment by avidale** [comment]
Hi @Fikavec! Thank you very much for this evidence. 
We are not planning to release the new SONAR text encoder (that could potentially fix your issue by data augmentation) in the foreseeable future. 

However, if your applications of SONAR require this problem to be solved, I could propose some practical ways to address it:

1. Include a script that normalizes the German spelling and capitalization as a data preprocessing step before feeding it to SONAR. This is generally a common practice; for example, the [preprocessing applied to all languages when training the NLLB translation model](https://github.com/facebookresearch/stopes/blob/main/stopes/pipelines/monolingual/monolingual_line_processor.py#L214) included punctuation normalization, replacing all non-printable characters with space, and replacing less common Unicode characters with their common variants according to NFKS rules, and the same preprocessing is recommended for its inference. In a German-specific application, it would make sense to add some German-specific preprocessing rules to the pipeline.

2. If you insist on having a SONAR text encoder which is by design insensitive to changes of spelling, you could probably distill a German-specific encoder (similarly to [how it was done with LASER 3 models](https://github.com/facebookresearch/fairseq/blob/nllb/examples/nllb/laser_distillation/README.md)) with extensive use of data augmentation that ensures the equivalence of alternative spelling forms. If you are interested in implementing this, we could probably help with setting the distillation script.

**Comment by lydianish** [comment]
Hello, and pardon my jumping in...

I am really interested in a LASER3-type distillation script, and would appreciate you setting it up.

Thanks  in advance!
________________________________

**Comment by Fikavec** [comment]
Hi @avidale! Thank you for your detailed response with the rules of preprocessing, as well as the work and support of such grandiose technological projects as SONAR and BLASER. I hope I didn't distract you too much from research and development and my small observations can be useful for the development of technology.
